package edu.ucla.cs.wis.bigdatalog.compiler.type;

public enum CompilerType {
	AGGREGATE,
	BASE_CLIQUE,
	BINDING_RELATION,
	BINDING,
	BUILT_IN_AGGREGATE,
	BUILT_IN_PREDICATE,	// APS added 6/5/2012
	CLIQUE_PREDICATE,
	CLIQUE,
	CLIQUE_PREDICATE_NODE,
	COMPILER_BOOLEAN,	 // APS added 12/5/2012	
	COMPILER_FLOAT,
	COMPILER_FUNCTOR,	// APS renamed 9/3/2013
	COMPILER_INT,
	COMPILER_LIST,
	COMPILER_TYPE_LIST,
	COMPILER_STRING,
	FS_AGGREGATE,	//APS added 2/25/2013
	DERIVED_PREDICATE,
	DERIVED_RELATION_NODE,
	EXPORT,		
	IFTHENELSE_PREDICATE,
	IFTHEN_PREDICATE,
	INPUT_VARIABLE,
	PCG_AND_NODE,
	PCG_NODE,
	PCG_OR_NODE,
	PREDICATE,
	PRIMED_PREDICATE_NODE,
	QUERY_FORM,
	BASIC_CLIQUE,
	BASE_NODE,
	RELATION,
	RULE,
	SCHEMA_COLUMN,
	SCHEMA_DEFINITION,
	SCHEMA_INDEX,
	SCHEMA_KEY,
	SCHEMA_RELATION,
	USER_DEFINED_AGGREGATE,
	VARIABLE,
	XY_CLIQUE_PREDICATE,
	XY_CLIQUE,
	COMPILER_NIL,
	COMPILER_LONG,
	COMPILER_LONGLONG,
	MODULE_DECLARATION,
	COMPILER_LONGLONGLONGLONG,
	COMPILER_DATETIME,
	CAST,
	ARITHMETIC_EXPRESSION,
	COMPILER_BYTE,
	COMPILER_SHORT,
	COMPILER_DOUBLE;
	
	public static boolean isInteger(CompilerType ct) {
		switch (ct) {
			case COMPILER_BYTE:
			case COMPILER_SHORT:
			case COMPILER_INT:
			case COMPILER_LONG:
				return true;
		}
		return false;
	}
}
